### PR TITLE
MUMUP-2398 : Add in generic robot gif

### PR DESCRIPTION
**Pull request by timlevett**
This little robot is the generic gif for our announcements, madison is the only school that has anything other than this now :

http://goo.gl/Vom3g5

http://goo.gl/3fpQkm

### CODE REVIEW

**Comment by timlevett** [comment]
Travis CI is a false positive build failure.

**Comment by Doug-Reed** [comment]
:+1:

**Comment by jhanstra** [comment]
Haha nice, I like it :+1:

**Comment by vertein** [comment]
:+1:

**Pull request merged**
