### PR TITLE
fix: correct misspelled 'surName' field

### PR DESCRIPTION
**Pull request by nblair**
Didn't find any uses where it was bound to views.

### CODE REVIEW

**Comment by vertein** [comment]
:+1:

**Comment by apetro** [comment]
:-1: pending hunting down how this is generated for reals.  Guest session and session are just example feeds; in production that's a live JSON feed out of uPortal, where that spelling error might or might not be a real thing.

**Comment by nblair** [comment]
surName isn't in the data model presented by `/portal/web/session.json`

```
{
person: {
lastName: "Blair",
userName: "npblair",
sessionKey: redacted,
serverName: redacted,
firstName: "Nicholas",
displayName: "Nicholas Blair",
version: "4.2.1.4"
}
}
```

**Comment by nblair** [comment]
It looks like I should change it to 'lastName' instead of 'surName'.

**Comment by nblair** [comment]
Force pushed an amended commit so that it's `lastName`.

**Comment by paulerickson** [comment]
:+1: for fixing typo, but I was hoping sirName was for heraldic titles or something :disappointed:

**Comment by nblair** [comment]
Weird build failure:

```
npm WARN engine hoek@2.16.3: wanted: {"node":">=0.10.40"} (current: {"node":"0.10.36","npm":"1.4.28"})
|> phantomjs-prebuilt@2.1.3 install /home/travis/build/UW-Madison-DoIT/uw-frame/node_modules/phantomjs-prebuilt
> node install.js
-JS at /usr/local/phantomjs/bin/phantomjs ...verifying
-JS detected, but wrong version 1.9.8 @ /usr/local/phantomjs/bin/phantomjs.
Downloading https://bitbucket.org/ariya/phantomjs/downloads/phantomjs-2.1.1-linux-x86_64.tar.bz2
Saving to /tmp/phantomjs/phantomjs-2.1.1-linux-x86_64.tar.bz2
Receiving...
-Error requesting archive.
Status: 403
Request options: {
  "uri": "https://bitbucket.org/ariya/phantomjs/downloads/phantomjs-2.1.1-linux-x86_64.tar.bz2",
  "encoding": null,
  "followRedirect": true,
  "headers": {
    "User-Agent": "npm/1.4.28 node/v0.10.36 linux x64"
  },
  "strictSSL": true
}
```

Any way to tell travis to try again?

**Comment by apetro** [comment]
Yes, you can tell Travis to try again. Doing.

re-try travis build

**Comment by timlevett** [comment]
:+1:

**Pull request merged**
