### PR TITLE
Add in cb specific styling

### PR DESCRIPTION
**Pull request by timlevett**
Created a CB specific style as the other ones were inconsistent depending on where you had cb.

### CODE REVIEW

**Comment by jhanstra** [comment]
Sweet. Does this fix the issue with uncenteredness of the icon? Can you screenshot?

**Comment by timlevett** [comment]
http://goo.gl/KJM0pj

**Comment by jhanstra** [comment]
Wooooo so much better

**Comment by keirserrie** [comment]
mmmmmm centery

**Pull request merged**
