### PR TITLE
Add in circle button directive

### PR DESCRIPTION
**Pull request by timlevett**
We use circle buttons a lot, lets just make a directive. I give you `<circle-button>`.

Options:
+ href : the href you want the anchor to have
+ target : the target (if blank, it'll launch in same window)
+ fa-icon : the fa-icon you want to use (e.g. fa-star)

Here is a demo:

image

### CODE REVIEW

**Comment by vertein** [comment]
:+1: I like that the whole circle is a button

**Comment by apetro** [comment]
:+1: :100: Excellent refactor.  Love it.  Exactly the kind of discovering and executing on opportunities for simplification and re-use that will keep us agile.

**Comment by keirserrie** [comment]
:+1:

**Comment by jhanstra** [comment]
late to the party, but :+1:

**Pull request merged**
