### PR TITLE
MUMUP-2141 : Add in undismiss

### PR DESCRIPTION
**Pull request by timlevett**
+ Fix empty state for the dismissed tab
+ Add in an undo dismiss action

http://goo.gl/8dctYP

http://goo.gl/Lf0oW2

_note my mouse capture was a little off, but all is well_

### CODE REVIEW

**Comment by vertein** [comment]
:+1:

**Comment by jhanstra** [comment]
:+1:

**Comment by keirserrie** [comment]
That icon reads as "reload" to me, but I see it's the official fontawesome "undo" icon so I will shut up now and give it :+1:

**Comment by apetro** [comment]
:+1: . Love it.  Tested on predev.

**Pull request merged**
