### PR TITLE
Documentation Syntax Highlighting

### PR DESCRIPTION
**Pull request by ChristianMurphy**
Add code block syntax flags.
Escape literal `_` characters in markdown.
Update example theme to used valid JSON double quotes.

----

Contributor License Agreement adherence:

- [x] This Contribution is under the terms of Individual [Contributor License Agreements][] (and also Corporate Contributor License Agreements to the extent applicable) appearing in the [Apereo CLA roster][].

[Apereo CLA roster]: http://licensing.apereo.org/completed-clas
[Contributor License Agreements]: https://www.apereo.org/licensing/agreements

### CODE REVIEW

**Comment by ChristianMurphy** [comment]
@davidmsibley Thanks for the pointer!
I merged with the `eslint-refactor` and replaced the `json` changes with the `javascript` and ESLint changes.

**Comment by ChristianMurphy** [comment]
and the eslint changes were squash merged...
I'll back the merge I did out, and reapply off new master.

**Comment by davidmsibley** [comment]
yup, sorry about that

**Comment by ChristianMurphy** [comment]
@davidmsibley No worries, updated branch with merge from master.

**Pull request merged**
