### PR TITLE
upgrade ui-bootstrap to 1.2.1 from 0.13.4

### PR DESCRIPTION
**Pull request by timlevett**
Copy of #171 but merge requested for 3.0.0 branch instead

### CODE REVIEW

**Comment by paulerickson** [comment]
:+1: but, FYI, the version in the 3.0.0-working-branch branch is 2.1.1-SNAPSHOT

**Comment by timlevett** [comment]
Heh, good point sir, fixing...

**Comment by vertein** [comment]
:+1:

**Comment by apetro** [comment]
:+1:

**Pull request merged**
