### PR TITLE
MUMUP-2353: Mobile burger menu looks yucky

### PR DESCRIPTION
**Pull request by jhanstra**
image

In Incognito, when What's New would show:
image

With search bar in focus: 
image

I'm not a huge fan of the black background - @keirserrie, did you have any suggestions for the background color? Everything else I tried wasn't really an improvement.

### CODE REVIEW

**Comment by timlevett** [comment]
looks neat, great progress! What's up with the big gap between the first entry and the header?

**Comment by jhanstra** [comment]
@timlevett it's to leave space for the search bar. I can't think of an easy way to have the menu be closer to the top without being covered up when you open search. Mostly because Bootstrap's mobile nav classes area a mess. Any ideas?

**Comment by timlevett** [comment]
Chatted f2f, decided to go with a variable that knows whether the the search is open or not. if it is, then add a class to the UL with the menu options to give it a big top padding. Should fix it.

**Comment by jhanstra** [comment]
@timlevett great idea, got it working
screen recording 2016-02-19 at 04 09 pm

**Comment by keirserrie** [comment]
@jhanstra - i had it mocked up on white bg, little more subtle and matches other dropdowns we use:

screenshot 2016-02-19 16 11 43

**Comment by jhanstra** [comment]
Ignore the fact that it looks like there's no padding on the right side - it's because my mouse is plugged in which puts in a scrollbar. See first screenshots for how it would actually look.

**Comment by jhanstra** [comment]
@keirserrie cool that does look much better. where is that mockup?

**Comment by jhanstra** [comment]
Also what color will the search bar be then? Dark border?

**Comment by apetro** [comment]
Consider darkening the background and making it a giant click surface for dismissing the menu.

Not-awesome mockup:

darken_me

**Comment by jhanstra** [comment]
Added a white background and used @apetro's idea for a box-shadow to draw focus. Didn't make the background a click surface as I think this may be difficult to do. Maybe worth revisiting that later?

I also just realized the mockup has black links...should I change them to black @keirserrie?

Screenshot:
image

**Comment by apetro** [comment]
Eh. If my tap in the box-shadow will "press through" to say launch email or Scheduling Assistant, then I think we're not ready for the box-shadow -- I think it really sets the user expectation that they can click in that space to dismiss the menu without taking action on the greyed out things.

**Comment by jhanstra** [comment]
One more screenshot. Thoughts?

image

**Comment by timlevett** [comment]
I say :shipit: :+1:

**Comment by jhanstra** [comment]
I think generally upper right is the default location for X's? Maybe not, @keirserrie thoughts? It does look less out of place when search is not active.

**Comment by vertein** [comment]
Maybe no 'X' and the close is just hitting the menu button again?

**Comment by jhanstra** [comment]
@vertein that's true already, but I don't think it's super obvious to the user.

**Comment by jhanstra** [comment]
:shipit: without 'x'

**Comment by timlevett** [comment]
:+1:

**Pull request merged**
