### PR TITLE
Upgrade to angular 1.5.6

### PR DESCRIPTION
**Pull request by timlevett**
+ Fixes build issue
+ Upgrade patch of angular

### CODE REVIEW

**Comment by vertein** [comment]
:+1:

**Comment by apetro** [comment]
What's going on with picking up the `animate` and `messages` dependencies?

**Comment by Doug-Reed** [comment]
👍

**Comment by timlevett** [comment]
@apetro - angular-material imports them. I'd rather layout all the angular that we are importing so we say when things are upgrades, where angular-material uses ^

**Pull request merged**
