### PR TITLE
Issue #379: Add ESLint as JavaScript Static Analysis and Linter

### PR DESCRIPTION
**Pull request by ChristianMurphy**
Part of #379 

----

Contributor License Agreement adherence:

- [x] This Contribution is under the terms of Individual [Contributor License Agreements][] (and also Corporate Contributor License Agreements to the extent applicable) appearing in the [Apereo CLA roster][].

[Apereo CLA roster]: http://licensing.apereo.org/completed-clas
[Contributor License Agreements]: https://www.apereo.org/licensing/agreements

### CODE REVIEW

**Comment by ChristianMurphy** [comment]
/cc @apetro @vertein @thevoiceofzeke @davidmsibley 

This PR is starting to fall out of sync.
Is there interest in applying Google Code style to `uw-frame`/`uPortal-app-framework` at this time?
Should this be reopened at a later date?

**Comment by davidmsibley** [comment]
We'll try to get this resolved soon.  I'll work on it today.

**Comment by davidmsibley** [comment]
There are too many failing eslint checks to merge into master at the moment, however I've created the eslint-refactor branch here: https://github.com/UW-Madison-DoIT/uw-frame/tree/eslint-refactor

Could you change the base branch to the eslint-refactor (or make a new PR if you can't) and resolve the current merge conflicts?  When that's ready, we can merge into there, and then I can work on the rest of the checks this sprint.

**Comment by ChristianMurphy** [comment]
branch retargeted, I'll be able to work through merge conflicts later today

**Comment by ChristianMurphy** [comment]
@davidmsibley c926097 reset the `uw-frame-components` folder to match current master, f4fda94 re-applies the automated lint fixes to the `master` version of the code.

**Comment by davidmsibley** [comment]
I think we actually lost some features in https://github.com/UW-Madison-DoIT/uw-frame/commit/c9260971c2f869613305c606ee1e6262b2a5aca6, did you pull from upstream into your master before merging?  If not, could you force reset to before the merge and try it again?

**Comment by ChristianMurphy** [comment]
@davidmsibley I reset the branch head to c926097 so the diff is easier to read. No features were lost.

**Comment by davidmsibley** [comment]
woah, ok, nevermind.  I'm not sure why it was looking so weird before...

**Comment by ChristianMurphy** [comment]
No worries, I re-added the automatic lint fixes in #423

**Comment by davidmsibley** [comment]
if we move ahead with #423, can we close this?

**Comment by ChristianMurphy** [comment]
Sure

**Pull request closed without merging**
