### PR TITLE
MUMUP-2337 : Change colors to match uw-system theme

### PR DESCRIPTION
**Pull request by timlevett**
Using https://www.wisconsin.edu/digital-communication/download/styleguide-5.27.15.pdf as a reference, changed the theme to look like this:

http://goo.gl/Y9q1JY

Note the colors that are weird in the body will be fixed in [another issue](https://jira.doit.wisc.edu/jira/browse/MUMUP-2268)

### CODE REVIEW

**Comment by vertein** [comment]
:+1:

**Comment by jhanstra** [comment]
:+1:

**Comment by keirserrie** [comment]
late to the game but :+1: may tweak that system logo at some point but not now

**Comment by timlevett** [comment]
Sounds good @keirserrie , I snagged there logo from https://www.wisconsin.edu/digital-communication/download/styleguide-5.27.15.pdf

**Pull request merged**
