### PR TITLE
dockerize all the things

### PR DESCRIPTION
**Pull request by timlevett**
+ Adds a Dockerfile that could be used as a base project for a static app
+ You could just run `FROM myuw/frame` and VOLUME in your my-app or copy, whatever

### CODE REVIEW

**Comment by vertein** [comment]
cool :+1:

**Comment by timlevett** [comment]
This is how we could use it: https://git.doit.wisc.edu/snippets/18

**Comment by timlevett** [comment]
Note this is using `http-server` and not superstatic. Sadly I was having issues getting superstatic to run in docker.

**Comment by timlevett** [comment]
Alright, with a bit more work, got superstatic working.

**Pull request merged**
