### PR TITLE
Updated UW-Extension theme: darkened @color3 to provide more contrast…

### PR DESCRIPTION
**Pull request by JoyceJohnston**
… against @color1; changed logo from CEOEL logo to generic UW-Extension logo

### CODE REVIEW

**Comment by vertein** [comment]
Looks good. Is the CEOEL logo unused now?  Could it be deleted?

**Comment by JoyceJohnston** [comment]
Yes it could. Should I do that and submit another merge request?

Thanks, Tim.

Joyce

**Comment by vertein** [comment]
If you would like, you can just edit this one by updating your branch.

**Comment by timlevett** [comment]
Please also update the themes version. Right now its 1, should be changed to 2

**Comment by JoyceJohnston** [comment]
Where is the themes version located?

**Comment by timlevett** [comment]
https://github.com/JoyceJohnston/uw-frame/blob/8a9ddd025570f58cb9ca9ff33a6e4dee96d2e060/uw-frame-components/js/frame-config.js#L7

**Comment by JoyceJohnston** [comment]
Ok Tim, I’ve committed those two changes — deleted the unneeded image and incrementing the theme version number.

Thanks,
Joyce

**Comment by vertein** [comment]
👍

**Pull request merged**
