### PR TITLE
Add in ng-cloak to the index pages, for better loading

### PR DESCRIPTION
**Pull request by timlevett**
Even with the loading splash, you can sometimes get a weird loading experience. This should help with that.

https://docs.angularjs.org/api/ng/directive/ngCloak

### CODE REVIEW

**Comment by vertein** [comment]
:+1: there's a note to add `angular-csp.css` to the html file.  I didn't read much farther down the page.  Is just copying the contents of this hypothetical file the preferred way?

**Comment by timlevett** [comment]
Thanks for the info @vertein . Looking into it, that is only if we are running in csp mode, which we are not.

**Comment by jhanstra** [comment]
:+1: awesome, seems legit. do you notice a difference @timlevett?

**Comment by timlevett** [comment]
Hard to tell on localhost, but curious what test looks like @jhanstra

**Comment by timlevett** [comment]
Well tested out on slow connections with the throttling in chrome dev tools. Seemed no better. Thanks for the thumbs, but this really doesn't do much for us.

**Comment by vertein** [comment]
Shucks, it seemed like it would have been nice.

**Pull request closed without merging**
