### PR TITLE
MUMUP-2441 UW-Stout theme

### PR DESCRIPTION
**Pull request by jiayinjx**
with color:#D18024
uw-stout-skin_screenshoot

### CODE REVIEW

**Comment by timlevett** [comment]
Looking at http://www.uwstout.edu/, it looks like some blue (the blue in the logo) is there primary (color1), and the other color is secondary (color2). @keirserrie ?

**Comment by keirserrie** [comment]
@jiayinjx - I updated the ticket with new logo & color

**Comment by keirserrie** [comment]
Save you a click--

#004990
[uw-stout-logo.png.zip](https://github.com/UW-Madison-DoIT/uw-frame/files/172212/uw-stout-logo.png.zip)

**Comment by jiayinjx** [comment]
Great! Thanks

**Comment by timlevett** [comment]
:+1: In the future, please do not work on themes until UX has provided the colors and logo.

**Pull request merged**
