### PR TITLE
MUMMNG-3332 "annoying" menu

### PR DESCRIPTION
**Pull request by davidmsibley**
menu off the bottom of the avatar, header underneath click catcher

----

Contributor License Agreement adherence:

- [x] This Contribution is under the terms of Individual [Contributor License Agreements][] (and also Corporate Contributor License Agreements to the extent applicable) appearing in the [Apereo CLA roster][].

[Apereo CLA roster]: http://licensing.apereo.org/completed-clas
[Contributor License Agreements]: https://www.apereo.org/licensing/agreements

### CODE REVIEW

**Comment by davidmsibley** [comment]
mummng-3332-1

**Comment by davidmsibley** [comment]
And just to show off cause I found a neat little gif recorder:
mummng-3332-2

**Comment by ChristianMurphy** [comment]
@davidmsibley which gif recorder did you use?

**Comment by davidmsibley** [comment]
Peek for linux: https://github.com/phw/peek

**Pull request merged**
