### PR TITLE
MUMUP-2156 : Add a logout link to header when sidebar is hidden

### PR DESCRIPTION
**Pull request by timlevett**
http://goo.gl/1ZLg0O

### CODE REVIEW

**Comment by vertein** [comment]
:+1:

**Comment by timlevett** [comment]
Resolves #41

**Comment by nblair** [comment]
Y no "Log out" text?

**Comment by timlevett** [comment]
@nblair - its in the title if they hover. Didn't want a lot of noise in the header. Worth revisiting if people complain :repeat:

**Comment by keirserrie** [comment]
Looks like screen reader will pick up title, so fine for now :+1:

**Pull request merged**
