### PR TITLE
Responsive marketplace styles

### PR DESCRIPTION
**Pull request by jhanstra**
Goes with https://github.com/UW-Madison-DoIT/angularjs-portal/pull/399

### CODE REVIEW

**Comment by Doug-Reed** [comment]
:+1:

**Comment by apetro** [comment]
Maybe a poor question: why are "Browse" styles here in `uw-frame` when the app directory browsing is an `angularjs-portal` feature?

**Comment by timlevett** [comment]
That is a very good point. We do have less in angularjs-portal :)

**Comment by jhanstra** [comment]
Yea, I did have an uneasy feeling making that change. I think they were originally there to keep all responsive styles in one place, i.e. only need one media query. But I'm thinking it's time to ditch that idea and put these styles in marketplace.less in `angularjs-portal`. Good call @apetro.

**Comment by timlevett** [comment]
I don't think having 2 media queries will break the bank will it?

**Comment by jhanstra** [comment]
Styles have been moved.

**Comment by timlevett** [comment]
Sometimes less is more :+1:

**Pull request merged**
