### PR TITLE
MUMUP-2298 : Add to home controller

### PR DESCRIPTION
**Pull request by timlevett**
Adds 2 variables to the `app-header` directive. 
+ Add to home flag
+ fname

Adds 3 things to `app-config.js`:
+ `NAMES.fname` - to be used if your app just have one marketplace entry and you want to use the add to home directive
+ `MISC_URLS.addToHomeURLS.layoutURL` - to be used to get the layout of the user to see if the user has this fname in there layout. Could be better if the server had a "has in layout" API call.
+ `MISC_URLS.addToHomeURLS.addToHomeActionURL` : the rest call to trigger when one clicks the button

### CODE REVIEW

**Comment by vertein** [comment]
:+1:

**Comment by timlevett** [comment]
after trying to use this in angularjs-portal, i think i found a bug if you are using the 2 way binding version. I may rearrange some things.

**Comment by timlevett** [comment]
alright, that should be better now.

**Comment by vertein** [comment]
Cool. :+1:

**Pull request merged**
