### PR TITLE
MUMUP-2255 : Coveralls support for uw-frame

### PR DESCRIPTION
**Pull request by timlevett**
+ Copied `package.json` from webapps dir to base. Needed still in webapps dir so that other projects can use it when running there tests
+ Added coveralls.io configuration into karma using the `karma-coveralls` package
+ added `npm test` to the travis ci scripts

### CODE REVIEW

**Comment by timlevett** [comment]
https://coveralls.io/github/UW-Madison-DoIT/uw-frame is configured, from what i read it can take up to 4 hours for it to start working.

**Comment by vertein** [comment]
Cool, so we just wait for the coverall-support branch to start working?

**Comment by timlevett** [comment]
So, looking at it a bit more, looks like the coveralls report is null, which is annoying. So, still working on this.

**Comment by timlevett** [comment]
http://goo.gl/ix5hwd

**Comment by apetro** [comment]
:+1: Awesome.

**Pull request merged**
